stages:
  - deploy

variables:
  GOPATH: /home/land/go

before_script:
  - export GOPATH=$GOPATH
  - export GOBIN=$GOPATH/bin
  - export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
  - cd $GOPATH/src
  - ln -sfn $CI_PROJECT_DIR $CI_PROJECT_NAME
  - cd vendor
  - if [ -z $Vendor ]; then git checkout master; git pull; else git pull; git checkout $Vendor;  fi
  - cd $GOPATH/src/$CI_PROJECT_NAME
  - ln -sfn $GOPATH/src/vendor vendor
  - cd $GOPATH/src

deploy_qa:
  stage: deploy
  tags:
    - deploy_go_qa
  script:
    - cd deploy
    - git pull
    - if [ -z $Project ]; then ./ci_deploy.sh $CI_PROJECT_NAME linux qa $CI_COMMIT_REF_NAME $Host; else ./ci_deploy.sh $Project linux qa $CI_COMMIT_REF_NAME $Host; fi
  environment:
    name: qa
  when: manual

deploy_stag:
  stage: deploy
  tags:
    - deploy_go_stag
  script:
    - cd deploy
    - git pull
    - if [ -z $Project ]; then ./ci_deploy.sh $CI_PROJECT_NAME linux stag $CI_COMMIT_REF_NAME $Host; else ./ci_deploy.sh $Project linux stag $CI_COMMIT_REF_NAME $Host; fi
  environment:
    name: stag
  when: manual

deploy_prod:
  stage: deploy
  tags:
    - deploy_go_prod
  script:
    - cd deploy
    - git pull
    - if [ -z $Project ]; then ./ci_deploy.sh $CI_PROJECT_NAME linux prod $CI_COMMIT_REF_NAME $Key $Host; else ./ci_deploy.sh $Project linux prod $CI_COMMIT_REF_NAME $Key $Host; fi
  environment:
    name: prod
  when: manual